name: "Remove Snap Completely"
description: "Remove the Snap package manager from Ubuntu runners on Github Actions."

branding:
  icon: "package"
  color: "orange"

runs:
  using: "composite"
  steps:
    - name: "run workflow script"
      shell: bash
      if: runner.os == 'Linux'
      run: |
        cd ${{ github.action_path }}
        sudo ./workflow.sh

