name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: run workflow script
        run: |
          sudo ./workflow.sh
      
      - name: test apt config
        run: |
          sudo apt-get upgrade -y
          sudo apt-get autoremove -y