name: testing
on: [push]

jobs:
  no_snapd:
    runs-on: ubuntu-latest

    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: run workflow script
        run: |
          sudo ./workflow.sh
      
      - name: test apt upgrading (no snapd)
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
  
  with_snapd:
    runs-on: ubuntu-latest

    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: test apt upgrading (with snapd)
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
